db_file: "bot.db"

message:
  responses:
    start: "Привет! Чтобы сохранять ссылки в своем Pocket аккаунте, для  начала тебе необходимо дать мне на это доступ. Для этого переходи по ссылке:\n%s"
    already_authorized: "Ты уже авторизован! Давай сохранять ссылки."
    saved_successfully: "Ссылка успешно сохранена 👍"
    unknown_command: "Я не знаю такой команды 😟"
  errors:
    invalid_url: "Это не валидная ссылка 😑"
    unauthorized: "Ты не авторизирован 🤔"
    unable_to_save: "Не удалось сохранить ссылку 😥"